name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    if: ${{ github.repository_owner == 'cloudflare' }}
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      issues: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # Pinned due to compatibility issues on 23.2.0
          node-version: "22"
          cache: "npm"

      - name: Install modules
        run: npm ci

      - name: Create Version PR
        id: changesets
        uses: changesets/action@v1
        with:
          createGithubReleases: true
          publish: npx changeset tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build action
        if: steps.changesets.outputs.published == 'true'
        run: npm run build

      - name: Push dist-tags
        if: steps.changesets.outputs.published == 'true'
        uses: JasonEtco/build-and-tag-action@v2
        with:
          tag_name: v${{ fromJSON(steps.changesets.outputs.publishedPackages)[0].version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
